# Generated by Django 5.1.3 on 2024-12-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0009_alter_problem_author_alter_problem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='자료 제목')),
                ('category', models.CharField(choices=[('알고리즘', '알고리즘'), ('자료구조', '자료구조'), ('수학', '수학'), ('기타', '기타')], max_length=50, verbose_name='카테고리')),
                ('description', models.TextField(verbose_name='자료 설명')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='첨부 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
