# Generated by Django 5.1.3 on 2024-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0010_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.RemoveField(
            model_name='data',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='data',
            name='content',
            field=models.TextField(default='기본 내용 없음'),
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(blank=True, choices=[('알고리즘', '알고리즘'), ('자료구조', '자료구조'), ('프로그래밍 언어', '프로그래밍 언어'), ('기타', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
