# Generated by Django 5.1.3 on 2024-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0002_remove_userprofile_user_name_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('options', models.TextField(blank=True, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
