# Generated by Django 5.1.3 on 2024-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBK_ossproject', '0008_blogpost_visibility_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contest_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='problem_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
